"""Installs a small `aipotluck-local-client` wrapper onto the system PATH, so the login/logout/
status CLI (aipotluck.installer.cli) is a real command rather than something only reachable from
inside this checkout with `python -m aipotluck.installer.cli`.

Not a pip console-script entry point: this project is never pip-installed -- the installer
downloads prebuilt llama.cpp/newt binaries rather than building anything, and there's no build
step or venv anywhere in this flow for a `[project.scripts]` entry point to hook into. Instead
this writes a tiny wrapper that directly execs the already-resolved Python interpreter against
cli.py's own file path -- the same "invoke the file directly, not via -m" pattern the OS service
registration already uses (ServiceManager.install() is handed aipotluck_service.py's path, not
`-m aipotluck.service.aipotluck_service`) -- which sidesteps needing PYTHONPATH or a specific CWD
for `-m` module resolution to work from an arbitrary shell.
"""

from __future__ import annotations

import ctypes
import logging
import os
import stat
from pathlib import Path

from aipotluck.installer.platform_detect import HostProfile

log = logging.getLogger("aipotluck.installer.cli_shim")

CLI_SHIM_NAME = "aipotluck-local-client"

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CLI_MODULE_PATH = REPO_ROOT / "aipotluck" / "installer" / "cli.py"


def _bin_dir(profile: HostProfile, system_scope: bool) -> Path:
    if profile.os_name == "windows":
        if system_scope:
            program_files = Path(os.environ.get("ProgramFiles", r"C:\Program Files"))
            return program_files / "aipotluck" / "bin"
        local_appdata = Path(os.environ.get("LOCALAPPDATA", str(Path.home() / "AppData" / "Local")))
        return local_appdata / "aipotluck" / "bin"
    # Linux/macOS: /usr/local/bin is on PATH everywhere without any shell config (why --system
    # uses it, matching --system already assuming elevation for the rest of the install); ~/.local/bin
    # is the standard per-user equivalent but isn't universally on PATH by default (notably not on a
    # bare macOS zsh) -- _ensure_on_path_posix below checks and warns rather than assuming it is.
    if system_scope:
        return Path("/usr/local/bin")
    return Path.home() / ".local" / "bin"


def _posix_shim_text(python_exe: Path) -> str:
    return (
        "#!/usr/bin/env bash\n"
        "# Generated by aipotluck-local-client's installer -- overwritten on every (re)install,\n"
        "# don't hand-edit. Runs the login/logout/status CLI with the exact interpreter the\n"
        "# installer resolved, regardless of what python3 happens to mean in this shell.\n"
        f'exec "{python_exe}" "{CLI_MODULE_PATH}" "$@"\n'
    )


def _windows_shim_text(python_exe: Path) -> str:
    return (
        "@echo off\r\n"
        "REM Generated by aipotluck-local-client's installer -- overwritten on every (re)install,\r\n"
        "REM don't hand-edit.\r\n"
        f'"{python_exe}" "{CLI_MODULE_PATH}" %*\r\n'
    )


def _ensure_on_path_posix(bin_dir: Path) -> None:
    path_entries = os.environ.get("PATH", "").split(os.pathsep)
    if str(bin_dir) in path_entries:
        return
    log.warning(
        "%s is not on your PATH yet, so `%s` won't be found until you add it. Add this to your "
        'shell profile (~/.bashrc, ~/.zshrc, ...) and open a new terminal:\n    export PATH="%s:$PATH"',
        bin_dir, CLI_SHIM_NAME, bin_dir,
    )


def _add_to_user_path_windows(bin_dir: Path) -> bool:
    """Best-effort: prepend bin_dir to HKCU\\Environment\\Path (persistent, no elevation needed)
    and broadcast WM_SETTINGCHANGE so already-open processes that listen for it pick it up --
    the same idiom real Windows installers use. A brand new shell always sees the change
    regardless; the broadcast just spares the *current* one a restart. Never raises -- a failed
    PATH edit is recoverable (the shim file itself is still written) and must not fail the whole
    install over it.

    STUB STATUS: implemented against documented Win32/registry behavior, not exercised on real
    Windows hardware (no Windows host available in this environment) -- same caveat as the rest
    of this repo's Windows path (see aipotluck/installer/python_bootstrap.py,
    aipotluck/installer/service/windows_service.py).
    """
    try:
        import winreg
    except ImportError:
        return False
    try:
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_READ | winreg.KEY_WRITE)
        try:
            try:
                current, _ = winreg.QueryValueEx(key, "Path")
            except FileNotFoundError:
                current = ""
            entries = [e for e in current.split(os.pathsep) if e]
            if str(bin_dir) in entries:
                return True
            winreg.SetValueEx(key, "Path", 0, winreg.REG_EXPAND_SZ, os.pathsep.join([str(bin_dir), *entries]))
        finally:
            winreg.CloseKey(key)

        HWND_BROADCAST, WM_SETTINGCHANGE, SMTO_ABORTIFHUNG = 0xFFFF, 0x1A, 0x0002
        ctypes.windll.user32.SendMessageTimeoutW(
            HWND_BROADCAST, WM_SETTINGCHANGE, 0, "Environment", SMTO_ABORTIFHUNG, 5000, None
        )
        return True
    except OSError as exc:
        log.warning("Could not add %s to your user PATH automatically (%s).", bin_dir, exc)
        return False


def install_cli_shim(profile: HostProfile, python_exe: Path, system_scope: bool) -> Path:
    """Writes the aipotluck-local-client wrapper and returns the path it wrote. Idempotent -- the
    file is fully rewritten every call, matching every other install step here. Best-effort on
    PATH itself: the shim is always written; whether it's *reachable* without an extra step is a
    warning (POSIX per-user, or Windows system-scope, where an automatic registry write needs
    elevation this process doesn't necessarily have) rather than a hard failure."""
    bin_dir = _bin_dir(profile, system_scope)
    bin_dir.mkdir(parents=True, exist_ok=True)

    if profile.os_name == "windows":
        shim_path = bin_dir / f"{CLI_SHIM_NAME}.cmd"
        shim_path.write_text(_windows_shim_text(python_exe), encoding="utf-8", newline="")
        if system_scope:
            log.warning(
                "%s is not necessarily on the machine-wide PATH. Add it via System Properties -> "
                "Environment Variables (System variables -> Path), or from an elevated shell: "
                'setx /M PATH "%%PATH%%;%s"',
                bin_dir, bin_dir,
            )
        elif not _add_to_user_path_windows(bin_dir):
            log.warning(
                "%s is not on your PATH and could not be added automatically. Add it via Settings -> "
                'System -> About -> Advanced system settings -> Environment Variables, or run: '
                'setx PATH "%%PATH%%;%s"',
                bin_dir, bin_dir,
            )
    else:
        shim_path = bin_dir / CLI_SHIM_NAME
        shim_path.write_text(_posix_shim_text(python_exe), encoding="utf-8")
        shim_path.chmod(shim_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        _ensure_on_path_posix(bin_dir)

    log.info("Installed %s -> %s", CLI_SHIM_NAME, shim_path)
    return shim_path
